/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

/**
 *
 * @author enri0
 */
public class frmProyect extends javax.swing.JFrame {
    
    private static final frmProyect instance = new frmProyect();
    
    //Se utiliza un constructor privado para evadir que el cliente use el constructor    
    private frmProyect(){
        initComponents();
    }
    
    public static frmProyect getInstance(){
        return instance;
    }
    
    String dato1 = new String();
    String signo = new String();
    String dato2 = new String();
    String cadena = new String();
    String test = new String();
    /**
     * Creates new form frmProyect
     */

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btndato = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btndato14 = new javax.swing.JButton();
        btndato15 = new javax.swing.JButton();
        btndato11 = new javax.swing.JButton();
        btndato13 = new javax.swing.JButton();
        btndato16 = new javax.swing.JButton();
        btndato18 = new javax.swing.JButton();
        btndato12 = new javax.swing.JButton();
        btndato17 = new javax.swing.JButton();
        btndato1 = new javax.swing.JButton();
        btndato2 = new javax.swing.JButton();
        btndato3 = new javax.swing.JButton();
        btndato4 = new javax.swing.JButton();
        btndato5 = new javax.swing.JButton();
        btndato6 = new javax.swing.JButton();
        btndato7 = new javax.swing.JButton();
        btndato8 = new javax.swing.JButton();
        btndato9 = new javax.swing.JButton();
        btndato21 = new javax.swing.JButton();

        jButton5.setText("-");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Calculadora");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 150, 122));
        jPanel1.add(btndato, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 139, 395, 66));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 210));

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));

        btndato14.setBackground(new java.awt.Color(153, 255, 255));
        btndato14.setText("-");
        btndato14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndato14ActionPerformed(evt);
            }
        });

        btndato15.setBackground(new java.awt.Color(153, 255, 255));
        btndato15.setText("+");
        btndato15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndato15ActionPerformed(evt);
            }
        });

        btndato11.setBackground(new java.awt.Color(153, 255, 255));
        btndato11.setText("*");
        btndato11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndato11ActionPerformed(evt);
            }
        });

        btndato13.setBackground(new java.awt.Color(153, 255, 255));
        btndato13.setText("/");
        btndato13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndato13ActionPerformed(evt);
            }
        });

        btndato16.setBackground(new java.awt.Color(153, 255, 255));
        btndato16.setText(".");
        btndato16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndato16ActionPerformed(evt);
            }
        });

        btndato18.setBackground(new java.awt.Color(153, 255, 255));
        btndato18.setText("1");
        btndato18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndato18ActionPerformed(evt);
            }
        });

        btndato12.setBackground(new java.awt.Color(153, 255, 255));
        btndato12.setText("=");
        btndato12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndato12ActionPerformed(evt);
            }
        });

        btndato17.setBackground(new java.awt.Color(153, 255, 255));
        btndato17.setText("CE");
        btndato17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndato17ActionPerformed(evt);
            }
        });

        btndato1.setBackground(new java.awt.Color(153, 255, 255));
        btndato1.setText("7");
        btndato1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndato1ActionPerformed(evt);
            }
        });

        btndato2.setBackground(new java.awt.Color(153, 255, 255));
        btndato2.setText("4");
        btndato2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndato2ActionPerformed(evt);
            }
        });

        btndato3.setBackground(new java.awt.Color(153, 255, 255));
        btndato3.setText("8");
        btndato3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndato3ActionPerformed(evt);
            }
        });

        btndato4.setBackground(new java.awt.Color(153, 255, 255));
        btndato4.setText("5");
        btndato4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndato4ActionPerformed(evt);
            }
        });

        btndato5.setBackground(new java.awt.Color(153, 255, 255));
        btndato5.setText("2");
        btndato5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndato5ActionPerformed(evt);
            }
        });

        btndato6.setBackground(new java.awt.Color(153, 255, 255));
        btndato6.setText("9");
        btndato6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndato6ActionPerformed(evt);
            }
        });

        btndato7.setBackground(new java.awt.Color(153, 255, 255));
        btndato7.setText("6");
        btndato7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndato7ActionPerformed(evt);
            }
        });

        btndato8.setBackground(new java.awt.Color(153, 255, 255));
        btndato8.setText("3");
        btndato8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndato8ActionPerformed(evt);
            }
        });

        btndato9.setBackground(new java.awt.Color(153, 255, 255));
        btndato9.setText("0");
        btndato9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndato9ActionPerformed(evt);
            }
        });

        btndato21.setBackground(new java.awt.Color(153, 255, 255));
        btndato21.setText("<");
        btndato21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndato21ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btndato2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(btndato4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndato7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndato17, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btndato14, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btndato1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btndato3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btndato15, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btndato6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btndato16, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btndato11, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btndato13, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btndato18, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btndato5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(btndato8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(btndato9, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btndato21, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(btndato12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndato14, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndato15, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndato11, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndato13, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btndato1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btndato6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btndato3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btndato16, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btndato2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btndato4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btndato7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btndato17, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndato5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndato18, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndato8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndato21, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndato9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndato12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 28, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 400, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndatoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btndatoActionPerformed

    private void btndato12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndato12ActionPerformed
        String resultado;
        dato2 = btndato.getText();
        if (!dato2.equals("")) {
        resultado = calculo(dato1,dato2,signo);
        btndato.setText(resultado);
    }
    }//GEN-LAST:event_btndato12ActionPerformed
    /* Se aplica el patron singleton en el metodo calculo porque es un metodo
    unico que realiza todas las funciones ademas de que indica al codigo de solo
    abrir una calculadora en vez de varias, la informacion usada en la calculadora
    es guardada en el cache del IDE para ser uasada antes de realizar una
    operacion con el boton igual (=).
    */
    public static String calculo(String dato1,String dato2, String signo){
        double resultado = 0.0;
        String respuesta;
        
        if (signo.equals("-")){
            resultado = Double.parseDouble(dato1)-Double.parseDouble(dato2);
            
        }
        if (signo.equals("+")){
            resultado = Double.parseDouble(dato1)+Double.parseDouble(dato2);
            
        }
        if (signo.equals("*")){
            resultado = Double.parseDouble(dato1)*Double.parseDouble(dato2);
            
        }
        if (signo.equals("/")){
            resultado = Double.parseDouble(dato1)/Double.parseDouble(dato2);
            
        }
        respuesta=String.valueOf(resultado);
        return respuesta;       }
    
    
    private void btndato14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndato14ActionPerformed
        dato1 = this.btndato.getText();
        signo = "-";
        this.btndato.setText("");
              
    }//GEN-LAST:event_btndato14ActionPerformed

    
    private void btndato15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndato15ActionPerformed
        dato1 = this.btndato.getText();
        signo = "+";
        this.btndato.setText("");
       
    }//GEN-LAST:event_btndato15ActionPerformed

    private void btndato11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndato11ActionPerformed
         dato1 = this.btndato.getText();
        signo = "*";
        this.btndato.setText("");
       
    }//GEN-LAST:event_btndato11ActionPerformed

    private void btndato13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndato13ActionPerformed
         dato1 = this.btndato.getText();
        signo = "/";
        this.btndato.setText("");
       
    }//GEN-LAST:event_btndato13ActionPerformed

    private void btndato16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndato16ActionPerformed
         String cadena;
         cadena = btndato.getText();
         
         if (cadena.length() <= 0) {
             btndato.setText("0.");
         }
         else{
             if (!existepunto(btndato.getText()))
                 btndato.setText(btndato.getText()+".");
         }
    }//GEN-LAST:event_btndato16ActionPerformed

    public static boolean existepunto(String cadena) {
        boolean resultado;
        resultado = false;
        
        for (int i = 0; i < cadena.length(); i++) {
            if (cadena.substring(1, i+1).equals(".")){
                resultado = true;
                break;
            }
            
        }
        return resultado;
    }
    
    private void btndato18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndato18ActionPerformed
        btndato.setText(btndato.getText()+"1");
    }//GEN-LAST:event_btndato18ActionPerformed

    private void btndato17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndato17ActionPerformed
        // TODO add your handling code here:
        btndato.setText("");
    }//GEN-LAST:event_btndato17ActionPerformed

    private void btndato1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndato1ActionPerformed
        // TODO add your handling code here:
        btndato.setText(btndato.getText()+"7");
    }//GEN-LAST:event_btndato1ActionPerformed

    private void btndato2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndato2ActionPerformed
        // TODO add your handling code here:
        btndato.setText(btndato.getText()+"4");
    }//GEN-LAST:event_btndato2ActionPerformed

    private void btndato3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndato3ActionPerformed
        // TODO add your handling code here:
        btndato.setText(btndato.getText()+"8");
    }//GEN-LAST:event_btndato3ActionPerformed

    private void btndato4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndato4ActionPerformed
        // TODO add your handling code here:
        btndato.setText(btndato.getText()+"5");
    }//GEN-LAST:event_btndato4ActionPerformed

    private void btndato5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndato5ActionPerformed
        // TODO add your handling code here:
        btndato.setText(btndato.getText()+"2");
    }//GEN-LAST:event_btndato5ActionPerformed

    private void btndato6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndato6ActionPerformed
        // TODO add your handling code here:
        btndato.setText(btndato.getText()+"9");
    }//GEN-LAST:event_btndato6ActionPerformed

    private void btndato7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndato7ActionPerformed
        // TODO add your handling code here:
        btndato.setText(btndato.getText()+"6");
    }//GEN-LAST:event_btndato7ActionPerformed

    private void btndato8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndato8ActionPerformed
        // TODO add your handling code here:
        btndato.setText(btndato.getText()+"3");
    }//GEN-LAST:event_btndato8ActionPerformed

    private void btndato9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndato9ActionPerformed
        // TODO add your handling code here:
        btndato.setText(btndato.getText()+"0");
    }//GEN-LAST:event_btndato9ActionPerformed

    private void btndato21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndato21ActionPerformed
        // TODO add your handling code here
        if (!btndato.getText().equals("")) {
            btndato.setText(btndato.getText().substring(0, btndato.getText().length()-1));
        }
        
    }//GEN-LAST:event_btndato21ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProyect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProyect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProyect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProyect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProyect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField btndato;
    public javax.swing.JButton btndato1;
    public javax.swing.JButton btndato11;
    public javax.swing.JButton btndato12;
    public javax.swing.JButton btndato13;
    public javax.swing.JButton btndato14;
    public javax.swing.JButton btndato15;
    public javax.swing.JButton btndato16;
    public javax.swing.JButton btndato17;
    public javax.swing.JButton btndato18;
    public javax.swing.JButton btndato2;
    public javax.swing.JButton btndato21;
    public javax.swing.JButton btndato3;
    public javax.swing.JButton btndato4;
    public javax.swing.JButton btndato5;
    public javax.swing.JButton btndato6;
    public javax.swing.JButton btndato7;
    public javax.swing.JButton btndato8;
    public javax.swing.JButton btndato9;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    }

